name: Build and Publish to NPM

on:
  push:
    branches:
      - main          

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.10.0'

    - name: Install Dependencies
      run: npm install
      
    - name: Unit Tests
      working-directory: packages/core
      run: npm test
      env:
        CI: true
    
    - name: Set up .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
    - name: Install dependencies
      run: npm ci
    
    #- name: Publish to npm
    #  i#f: github.actor == 'rsaz'
    #  uses: JS-DevTools/npm-publish@v1
    #  with:
    #    token: $#{{ secrets.NPM_TOKEN }}
    #    tag: latest
    #    access: public 
   